version: '3'

services:
  24.04-mise:
    build:
      context: ubuntu-mise/
      dockerfile: Dockerfile
      args:
        - UBUNTU_VERSION=24.04
      x-bake:
        platforms:
          - "linux/amd64"
          - "linux/arm64"
        tags:
          - "${REPOSITORIES}/ubuntu-mise:24.04"
  22.04-mise:
    build:
      context: ubuntu-mise/
      dockerfile: Dockerfile
      args:
        - UBUNTU_VERSION=22.04
      x-bake:
        platforms:
          - "linux/amd64"
          - "linux/arm64"
        tags:
          - "${REPOSITORIES}/ubuntu-mise:22.04"
