ARG UBUNTU_VERSION
FROM ubuntu:${UBUNTU_VERSION}

USER root
RUN useradd -rm -d /home/ubuntu -s /bin/bash -U -G sudo ubuntu || true
RUN apt-get update && \
    apt-get install -y curl git rsync openssh-client ca-certificates && \
    dpkg --configure -a || true
RUN echo "StrictHostKeyChecking no" | tee -a /etc/ssh/ssh_config

USER ubuntu

RUN mkdir -p ~/.local/bin/
RUN curl https://mise.run | MISE_INSTALL_PATH=~/.local/bin/mise sh

# Installs mise and adds activation to ~/.bashrc
RUN echo 'eval "$(~/.local/bin/mise activate bash)"' >> ~/.bashrc
RUN echo 'eval "$(~/.local/bin/mise activate bash)"' >> ~/.profile
ENTRYPOINT ["/bin/bash", "--login", "-c"]