ARG UBUNTU_VERSION
FROM ubuntu:${UBUNTU_VERSION}

USER root
RUN useradd -rm -d /home/ubuntu -s /bin/bash -U -G sudo ubuntu || true
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl git rsync openssh-client && \
    dpkg --configure -a || true
RUN echo "StrictHostKeyChecking no" | tee -a /etc/ssh/ssh_config

USER ubuntu

RUN curl -fsSL https://mise.jdx.dev/install.sh | sh
RUN echo 'eval "$(~/.local/bin/mise activate bash)"' >> ~/.bashrc
RUN echo 'eval "$(~/.local/bin/mise activate bash)"' >> ~/.profile
ENTRYPOINT ["/bin/bash", "--login", "-c"]