name: build image
run-name: ${{ github.actor }} start build image

on: 
  pull_request:
    branches: [ "main" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '1 0 * * 1'
jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build mise image
        run: docker buildx bake -f docker-compose.yaml --pull --push --progress plain --no-cache
