name: build ubuntu mise image

on: 
  # pull_request:
  #   branches: [ "main" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '1 0 * * 1'
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build ubuntu mise image
        run: docker buildx bake -f ubuntu-mise.docker-compose.yaml --pull --push --progress plain --no-cache
